### ISSUE TITLE
The request was aborted: Could not create SSL\TLS secure channel

### ISSUE THREAD

**Issue by capnchamomile** [dkschruteBeets/Pax8-API#1]
Getting this error after I connect to Pax8 and try to pull a subscription by ID 

![image](https://user-images.githubusercontent.com/25969971/186710274-5cf68cb5-9dd7-45bb-9cd8-0133cc77e555.png)

**Comment by dkschruteBeets** [comment]
Run this line before you pull a subscription ID:

`[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12`

If that works, I may need to add this into the request for folks not using TLS 1.2 on their machine.

**Comment by capnchamomile** [comment]
Gave that a shot but no go. 

![image](https://user-images.githubusercontent.com/25969971/186722685-c8b44fb7-4d91-46a9-a17f-828f6d58a809.png)

This is an older machine running Windows Server 2012 R2 but I was able to use this module on this machine successfully in the past. The module works fine on my Windows 10 machine as well.

**Comment by dkschruteBeets** [comment]
That's strange. Maybe a recent update? Have you looked at IISCrypto on that server? I'm curious to see what is currently checked under Schannel (the greyed out defaults).

**Comment by capnchamomile** [comment]
Looks like all the defaults are greyed out. Internet Options is set to use TLS 1.0, 1.1, and 1.2. All SSL versions are disabled. 

Very odd. I'll reboot it tonight and follow up if it's still messed up tomorrow. Thanks for your help :)

**Comment by dkschruteBeets** [comment]
Not a problem!
