### ISSUE TITLE
Update-Pax8SubscriptionById

### ISSUE THREAD

**Issue by Danpoulter97** [dkschruteBeets/Pax8-API#2]
Not sure whether this is an issue with the Module or Pax8 but I cannot use the Update-Pax8SubscriptionById. I get the below error: 
`Invoke-Pax8MasterRequest : The remote server returned an error: (500) Internal Server Error.`

I am using the latest version of the PS Module.

**Comment by dkschruteBeets** [comment]
That's typically an issue with the REST server. Can you make the call manually? Use the code snippet below with your values:
```
# Update these variables with your values
$accessToken = "Your access token here"
$subscriptionId = "Your subscription Id here"

$headers = New-Object "System.Collections.Generic.Dictionary[[String],[String]]"
$headers.Add("Content-Type", "application/json")
$headers.Add("Authorization", "Bearer $accessToken")

# Update the body to reflect your values
$body = @"
{
    "quantity":11,
    "startDate":"2020-02-10",
    "endDate":"2021-08-24",
    "price":15.39,
    "billingTerm":"Monthly",
    "provisioningDetails":[
        {
            "key":"userEmailAddress",
            "values":[
                "joeysherp@example.com"
            ]
        }
    ]
}
"@

$response = Invoke-RestMethod "https://api.pax8.com/v1/subscriptions/$($subscriptionId)" -Method 'PUT' -Headers $headers -Body $body
$response | ConvertTo-Json
```

**Comment by Danpoulter97** [comment]
Hi, thanks for the help - when I call it manually I get the same error. I assume I will need to go back to Pax8?

**Comment by dkschruteBeets** [comment]
No problem. Yeah, it sounds like it could be an issue on their end so I'd reach out to them. Let me know if I can help with anything else once you hear back.

**Comment by Danpoulter97** [comment]
Before I could raise a ticket with Pax8 the code both the REST code and PowerShell module have both started working so all sorted now - thanks for the help!
