### ISSUE TITLE
Country now a required field

### ISSUE THREAD

**Issue by DirectITServicesUK** [dkschruteBeets/Pax8-API#3]
Country is now a required field for adding a new client.

**Comment by dkschruteBeets** [comment]
Where are you seeing this? I looked in the API docs and I don't see that field as being required anywhere.

**Comment by DirectITServicesUK** [comment]
![image](https://user-images.githubusercontent.com/100635373/201987058-9375c1b5-c1d5-4b4b-878b-06587b478f29.png)

![image](https://user-images.githubusercontent.com/100635373/201987148-eeee0c30-b00a-4648-8bd9-f145d51b0669.png)

**Comment by DirectITServicesUK** [comment]
It's in the API docs "example" but not in the main doc

**Comment by dkschruteBeets** [comment]
Ah, good catch. I'll get that fixed as well shortly.

**Comment by dkschruteBeets** [comment]
I updated the example docs to include 'country'. The address parameter itself is already mandatory so hopefully the updated example helps.
