### ISSUE TITLE
Cannot add new client - Name Cannot Be Blank?

### ISSUE THREAD

**Issue by DirectITServicesUK** [dkschruteBeets/Pax8-API#4]
Regardless of whether I put a variable in or hard code this, it refuses to work.
New-Pax8Company -name "This is a test really" 

![image](https://user-images.githubusercontent.com/100635373/201975839-95d7b179-f444-423b-8645-4f9b12ba46fc.png)

**Comment by dkschruteBeets** [comment]
Looks like I have a typo here:

![image](https://user-images.githubusercontent.com/103469370/201985905-4db75c86-7ecc-4c1e-8b4f-e6b97cf4ea8b.png)

This should be 'name'. I'll get that fixed in a few.

**Comment by dkschruteBeets** [comment]
New version released. This should be fixed now.
